### ISSUE TITLE
Websocket connection fails when behind reverse proxy w/TLS

### ISSUE THREAD

**Issue by scottt732** [ESPresense/ESPresense#1157]
### Describe the bug

I use a reverse proxy for tls & proxying traffic to my espresense nodes. The config & ui pages work fine, but the websocket connection fails on the devices page here:

```
new WebSocket(`${location.origin.replace("http://", "ws://")}/ws`))
```

Since my `window.location.origin` starts with `https://`, the replace doesn't happen. I need `wss://` instead of `ws://`.

This is the error I see in the browser console:

```
index.js:1  Uncaught (in promise) DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'https' is not allowed.
    at https://espr1.myhouse.com/ui/index.js:1:22244
    at Object.subscribe (https://espr1.myhouse.com/ui/index.js:1:6827)
    at o (https://espr1.myhouse.com/ui/index.js:1:393)
    at i (https://espr1.myhouse.com/ui/index.js:1:491)
    at zt (https://espr1.myhouse.com/ui/index.js:1:50277)
    at _e (https://espr1.myhouse.com/ui/index.js:1:5493)
    at new /devices (https://espr1.myhouse.com/ui/index.js:1:108185)
    at A (https://espr1.myhouse.com/ui/index.js:1:2750)
    at Object.p (https://espr1.myhouse.com/ui/index.js:1:8113)
    at Object.p (https://espr1.myhouse.com/ui/index.js:1:9277)
```

### Version

3.3.1

### Active scan enabled

n/a

### Include filter

n/a

### Exclude filter

n/a

### Query filter

n/a

### Firmware flavor

m5atom

### Device (be specific)

M5 ATOM Lite

### Screenshots

![image](https://github.com/ESPresense/ESPresense/assets/197019/640e7ed7-9af7-4ce7-9228-5d5f8f6fea5c)

**Comment by scottt732** [comment]
MR was merged. This was fixed. Thanks! Just doing some housekeeping.
